-- =========================================
--  Initial Resource Seed Data (PostgreSQL)
-- =========================================
-- Insert resources
INSERT INTO resources (
        resource_id,
        department_id,
        name,
        description,
        total_quantity,
        available_quantity,
        resource_type,
        category,
        resource_kind,
        status,
        unit,
        is_trackable,
        latitude,
        longitude,
        last_location_update,
        current_deployment_id,
        deployed_quantity,
        image,
        created_at,
        updated_at
    )
VALUES (
        1,
        1,
        'Fire Truck A1',
        'Primary fire response vehicle with 5000L capacity',
        NULL,
        NULL,
        'FIRE_TRUCK',
        'VEHICLE',
        'UNIQUE',
        'AVAILABLE',
        'UNITS',
        true,
        52.2215,
        6.8937,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        2,
        1,
        'Ladder Truck L2',
        'Hydraulic ladder truck with 30m reach',
        NULL,
        NULL,
        'FIRE_TRUCK',
        'VEHICLE',
        'UNIQUE',
        'AVAILABLE',
        'UNITS',
        true,
        52.2208,
        6.8902,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        3,
        1,
        'Rescue Operator Team',
        'Trained firefighters for rescue operations',
        8,
        8,
        'TEAM',
        'EQUIPMENT',
        'STACKABLE',
        'AVAILABLE',
        'UNITS',
        false,
        52.2220,
        6.8911,
        NOW(),
        NULL,
        0,
        NULL,
        NOW(),
        NOW()
    ),
    (
        4,
        2,
        'Patrol Car P1',
        'Standard police patrol vehicle',
        NULL,
        NULL,
        'PATROL_CAR',
        'VEHICLE',
        'UNIQUE',
        'DEPLOYED',
        'UNITS',
        true,
        52.2180,
        6.8965,
        NOW(),
        1001,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        5,
        2,
        'Riot Response Unit',
        'Specialized team for crowd control and riots',
        10,
        10,
        'TEAM',
        'EQUIPMENT',
        'STACKABLE',
        'AVAILABLE',
        'UNITS',
        false,
        52.2175,
        6.8959,
        NOW(),
        NULL,
        0,
        NULL,
        NOW(),
        NOW()
    ),
    (
        6,
        2,
        'Transport Van',
        'Used to transport personnel or detainees',
        NULL,
        NULL,
        'TRANSPORT_TRUCK',
        'VEHICLE',
        'UNIQUE',
        'MAINTENANCE',
        'UNITS',
        true,
        52.2189,
        6.8940,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        7,
        3,
        'Ambulance A1',
        'Emergency ambulance with advanced life support',
        NULL,
        NULL,
        'AMBULANCE',
        'VEHICLE',
        'UNIQUE',
        'AVAILABLE',
        'UNITS',
        true,
        52.2230,
        6.8885,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        8,
        3,
        'Ambulance A2',
        'Basic ambulance for patient transfer',
        NULL,
        NULL,
        'AMBULANCE',
        'VEHICLE',
        'UNIQUE',
        'AVAILABLE',
        'UNITS',
        true,
        52.2227,
        6.8897,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        9,
        3,
        'Medical Staff',
        'Doctors and nurses available for emergency',
        20,
        20,
        'TEAM',
        'EQUIPMENT',
        'STACKABLE',
        'AVAILABLE',
        'UNITS',
        false,
        52.2240,
        6.8871,
        NOW(),
        NULL,
        0,
        NULL,
        NOW(),
        NOW()
    ),
    (
        10,
        4,
        'Maintenance Van',
        'Used for city infrastructure maintenance',
        NULL,
        NULL,
        'TRANSPORT_TRUCK',
        'VEHICLE',
        'UNIQUE',
        'AVAILABLE',
        'UNITS',
        true,
        52.2260,
        6.8830,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ),
    (
        11,
        4,
        'Repair Crew',
        'Team responsible for electrical and plumbing repairs',
        5,
        5,
        'TEAM',
        'EQUIPMENT',
        'STACKABLE',
        'AVAILABLE',
        'UNITS',
        false,
        52.2271,
        6.8842,
        NOW(),
        NULL,
        0,
        NULL,
        NOW(),
        NOW()
    ),
    (
        12,
        4,
        'Water Pump Vehicle',
        'Used during city floods and emergencies',
        NULL,
        NULL,
        'WATER_TANKER',
        'VEHICLE',
        'UNIQUE',
        'AVAILABLE',
        'UNITS',
        true,
        52.2254,
        6.8827,
        NOW(),
        NULL,
        NULL,
        NULL,
        NOW(),
        NOW()
    ) ON CONFLICT (resource_id) DO NOTHING;
-- Prevent duplicate inserts if script runs multiple times
-- Reset sequence to avoid conflicts
SELECT setval(
        'resources_resource_id_seq',
        (
            SELECT MAX(resource_id)
            FROM resources
        )
    );