# =======================================
# PROD PROFILE
# =======================================
# Enable Eureka for service discovery
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=region-service
spring.cloud.discovery.enabled=true
# Logging cleaner in production
logging.level.org.springframework=WARN
logging.level.nl.saxion.disaster=INFO
