# =======================================
# DEPARTMENT SERVICE CONFIG (LOCAL DOCKER)
# =======================================


# ---------------------------------------
# Eureka
# ---------------------------------------
eureka.client.enabled=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.hostname=department-service
spring.cloud.discovery.enabled=true


# ---------------------------------------
# Kafka
# ---------------------------------------
spring.kafka.bootstrap-servers=kafka:9092


# ---------------------------------------
# Datasource (local-docker)
# ---------------------------------------
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://postgres-db:5432/department_db
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# ---------------------------------------
# Hibernate / JPA
# ---------------------------------------
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
