# =======================================
# DEPARTMENT SERVICE CONFIG (LOCAL SINGLE)
# =======================================


# ---------------------------------------
# Eureka (disabled for single-service local run)
# ---------------------------------------
eureka.client.enabled=false
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
spring.cloud.discovery.enabled=false


# ---------------------------------------
# Kafka
# ---------------------------------------
spring.kafka.bootstrap-servers=localhost:9092


# ---------------------------------------
# Datasource (local-single)
# ---------------------------------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/department_db
spring.datasource.username=postgres
spring.datasource.password=1234


# ---------------------------------------
# Hibernate / JPA
# ---------------------------------------
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
