# ========================================
# H2 In-Memory Database (For Tests)
# ========================================
spring.datasource.url=jdbc:h2:mem:department-test-db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# ========================================
# JPA / Hibernate for Tests
# ========================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# ========================================
# SQL Initialization
# ========================================
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
# ========================================
# Disable DevTools reload (faster test startup)
# ========================================
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
# ========================================
# Randomize Port to avoid conflicts
# ========================================
eureka.client.enabled=false

spring.kafka.enabled=false
spring.kafka.producer.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server.port=0
