# =======================================
# DEPARTMENT SERVICE CONFIG (PROD)
# =======================================


# ---------------------------------------
# Logging
# ---------------------------------------
logging.level.nl.saxion.disaster=INFO
logging.level.org.springframework=WARN


# ---------------------------------------
# Eureka
# ---------------------------------------
eureka.client.enabled=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://discovery-service.drccs.local:8761/eureka/
eureka.instance.hostname=department-service
eureka.instance.prefer-ip-address=false
spring.cloud.discovery.enabled=true


# ---------------------------------------
# Datasource
# ---------------------------------------
spring.datasource.url=jdbc:postgresql://drccs-db.cv24ewc6mmoj.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# ---------------------------------------
# Kafka
# ---------------------------------------
spring.kafka.bootstrap-servers=kafka.drccs.local:9092


# ---------------------------------------
# Hibernate / JPA
# ---------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
