
-- ============================
-- Initial Data for Departments
-- ============================

-- 🔥 Fire Department Icon (shared Base64)
-- 🚔 Police Department Icon (shared Base64)
-- 🏥 Medical Department Icon (shared Base64)

-- Fire
-- iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANBJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC
-- Police
-- iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANtJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC
-- Medical
-- iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAAKdJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC

-- Deventer
INSERT INTO department (municipality_id, name, image, created_at, updated_at) VALUES
(1, 'Fire Department Deventer',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANBJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now()),
(1, 'Police Department Deventer',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANtJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now()),
(1, 'Medical Department Deventer',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAAKdJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now());

-- Enschede
INSERT INTO department (municipality_id, name, image, created_at, updated_at) VALUES
(2, 'Fire Department Enschede',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANBJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now()),
(2, 'Police Department Enschede',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANtJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now()),
(2, 'Medical Department Enschede',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAAKdJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now());

-- Zwolle
INSERT INTO department (municipality_id, name, image, created_at, updated_at) VALUES
(3, 'Fire Department Zwolle',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANBJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now()),
(3, 'Police Department Zwolle',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAANtJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now()),
(3, 'Medical Department Zwolle',
 decode('iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAAAvf+5AAAAAAXNSR0IArs4c6QAAAKdJREFUKFNjZICC////PwMYGBgYPwMDQyMjY1iYGJwBxMEZGJiAqP3///8/YIiA+zYGwRAxwLS2tnVhYGAQl6FhXgWSr2NqAADTAEJrMTEyMf1BhACxmpqaoRrBywNDA8Q8Rg4h0RyIDqZ2BgYMyAqgkEb+Ap7NwMDA8QNODCwCAOCCiYoG4mTAwMDw/RgAizxZgRAwAFoHBsC8UgBtAAAAAElFTkSuQmCC', 'base64'),
 now(), now());
