# =======================================
# CHAT SERVICE CONFIG
# =======================================

# ---------------------------------------
# Actuator
# ---------------------------------------
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info


# ---------------------------------------
# Server
# ---------------------------------------
server.address=0.0.0.0
spring.application.name=chat-service
server.port=8089


# ---------------------------------------
# Feign
# ---------------------------------------
logging.level.org.springframework.cloud.openfeign=DEBUG
spring.cloud.openfeign.enabled=true


# ---------------------------------------
# Logging
# ---------------------------------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE


# ---------------------------------------
# Error handling
# ---------------------------------------
server.error.include-binding-errors=always
server.error.include-message=always

# Keycloak
# ---------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:9090/realms/DRCCS
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:9090/realms/DRCCS/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.allowed-issuers=http://localhost:9090/realms/DRCCS
