# --------------------------------------------------
# Server Configuration
# --------------------------------------------------
server.port=8083

# --------------------------------------------------
# Application Info
# --------------------------------------------------
spring.application.name=notification-service

# --------------------------------------------------
# Logging
# --------------------------------------------------
logging.level.root=INFO
logging.level.nl.saxion.disaster.notificationservice=DEBUG

# --------------------------------------------------
# Municipality service URL (for later use)
# --------------------------------------------------
municipality.service.url=http://municipality-service:8082

