version: '3.9'

services:
  department-service:
    build: ./department-service
    container_name: department-service
    ports:
      - "8081:8081"
    networks:
      - backend-network

  municipality-service:
    build: ./municipality-service
    container_name: municipality-service
    ports:
      - "8082:8082"
    depends_on:
      - department-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
