# =======================================
# PROD PROFILE
# =======================================
# Enable Eureka for service discovery
eureka.client.enabled=true
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.discovery.enabled=true
# Logging for production
logging.level.org.springframework=WARN
logging.level.nl.saxion.disaster=INFO
