# =======================================
# DEV PROFILE
# =======================================
# Disable Eureka (faster local testing)
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.discovery.enabled=false
# Logging for development
logging.level.org.springframework=INFO
logging.level.nl.saxion.disaster=DEBUG
